[verilog-stdlib]
git-tree-sha1 = "9e61722e65844bf89a8e48474bbcdcbe2b3d7c19"
lazy = true

    [[verilog-stdlib.download]]
    sha256 = "bd36c6bfc9280de22cba2ab66a30f526aea6d3ca2578401f9b1d5f4f791c4db5"
    url = "https://github.com/UW-PHARM/BitSAD.jl/raw/v0.1.0/verilog-stdlib.tar.gz"
    [[verilog-stdlib.download]]
    sha256 = "bd36c6bfc9280de22cba2ab66a30f526aea6d3ca2578401f9b1d5f4f791c4db5"
    url = "https://github.com/UW-PHARM/BitSAD.jl/raw/master/verilog-stdlib.tar.gz"
