[verilog-stdlib]
git-tree-sha1 = "118a96966266c9bcecec30c946fe874cb9b77b80"
lazy = true

    [[verilog-stdlib.download]]
    sha256 = "43f36a3895ca47c50fbf2d8b9f0c71aa18856364afb15b1c3d1ea814fd7cfd48"
    url = "https://github.com/UW-PHARM/BitSAD.jl/raw/v0.1.0/verilog-stdlib.tar.gz"
    [[verilog-stdlib.download]]
    sha256 = "43f36a3895ca47c50fbf2d8b9f0c71aa18856364afb15b1c3d1ea814fd7cfd48"
    url = "https://github.com/UW-PHARM/BitSAD.jl/raw/master/verilog-stdlib.tar.gz"
